In [1]:
import numpy as np

In [3]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.insert(a, 1, 50)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.insert(a, (1,4), 50)

array([ 1, 50,  2,  3,  4, 50,  5,  6,  7,  8,  9, 10])

In [6]:
import numpy as np

In [7]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
np.insert(a, 1, 34, axis=0)

array([[ 1,  2],
       [34, 34],
       [ 3,  4]])

In [9]:
np.insert(a, 1, 34, axis=1)

array([[ 1, 34,  2],
       [ 3, 34,  4]])

In [10]:
np.insert(a, 1, [2, 5], axis=0)

array([[1, 2],
       [2, 5],
       [3, 4]])

In [11]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.append(a, 234)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 234])

In [13]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [14]:
np.append(a, [[2,9]], axis=-0)

array([[1, 2],
       [3, 4],
       [2, 9]])

In [15]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.delete(a, 3)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])