In [1]:
import numpy as np

In [2]:
a = np.array([[3,1],[1,2]])
a

array([[3, 1],
       [1, 2]])

In [3]:
b = np.array([9, 8])
b

array([9, 8])

In [4]:
np.linalg.solve(a, b)

array([2., 3.])

In [5]:
import numpy as np

In [6]:
a = np.array("3 5;6 9")
a

array('3 5;6 9', dtype='<U7')

In [7]:
a = np.array([[3, 6], [9, 2]])
a

array([[3, 6],
       [9, 2]])

In [8]:
np.linalg.det(a)

-48.00000000000001