In [1]:
import numpy as np

In [2]:
a = np.array([[1, 3], [5, 6]])
a

array([[1, 3],
       [5, 6]])

In [3]:
b = np.array([[8, 7], [9, 2]])
b

array([[8, 7],
       [9, 2]])

In [4]:
a+b

array([[ 9, 10],
       [14,  8]])

In [5]:
a*b

array([[ 8, 21],
       [45, 12]])

In [6]:
a.dot(b)

array([[35, 13],
       [94, 47]])

In [1]:
import numpy as np

In [2]:
a = np.matrix("1 3;5 6")
a

matrix([[1, 3],
        [5, 6]])

In [3]:
a.T

matrix([[1, 5],
        [3, 6]])

In [4]:
b = np.linalg.inv(a)
b

matrix([[-0.66666667,  0.33333333],
        [ 0.55555556, -0.11111111]])

In [5]:
a = np.matrix("1 2;3 4")
a

matrix([[1, 2],
        [3, 4]])

In [7]:
b = np.linalg.inv(a)
b

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [8]:
import numpy as np

In [9]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
b = np.linalg.matrix_power(a, 2)
b

array([[ 7, 10],
       [15, 22]])

In [11]:
b = np.linalg.matrix_power(a, -2)
b

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])